// AUTO-GENERATED BY scripts/add-practice.mjs
window.CLASSROOM_PRACTICE_ITEMS = [
  {
    "id": "courseware-2026-07-23-special-questions",
    "title": "26.07.23｜特殊疑问句专项课",
    "description": "特殊疑问句专项课随堂练习，共20题，覆盖疑问词选择、be/do/does路线与Who主语例外",
    "icon": "screen",
    "tone": "purple",
    "path": "courseware/26.07.23｜特殊疑问句专项课.html"
  },
  {
    "id": "courseware-2026-07-22-simple-present-2",
    "title": "26.07.22｜一般现在时第二课",
    "description": "一般现在时第二课随堂练习，共20题，覆盖否定句、一般疑问句与简短回答",
    "icon": "screen",
    "tone": "purple",
    "path": "courseware/26.07.22｜一般现在时第二课.html"
  },
  {
    "id": "courseware-2026-07-17-articles",
    "title": "26.07.17｜冠词闯关",
    "description": "冠词课堂即时练习，共 24 题，覆盖 a/an、the、零冠词与易混辨析",
    "icon": "screen",
    "tone": "purple",
    "path": "courseware/26.07.17｜冠词闯关.html"
  },
  {
    "id": "courseware-2026-07-17",
    "title": "26.07.17｜名词变身工厂",
    "description": "名词单复数课堂即时练习，共 14 题",
    "icon": "screen",
    "tone": "purple",
    "path": "courseware/26.07.17｜名词变身工厂.html"
  },
  {
    "id": "courseware-2026-07-16",
    "title": "26.07.16｜语法车站：代词 + be 动词",
    "description": "代词与 be 动词课堂即时练习",
    "icon": "screen",
    "tone": "purple",
    "path": "courseware/26.07.16.html"
  },
  {
    "id": "sentence-structure-2026-07-15",
    "title": "26.07.15｜句子骨架与句型变身",
    "description": "句子骨架、句型判断、句型转换与扩句练习",
    "icon": "screen",
    "tone": "purple",
    "path": "courseware/26.07.15.html"
  }
];
// Legacy alias: keep existing integrations and historical pages working.
window.COURSEWARE_ITEMS = window.CLASSROOM_PRACTICE_ITEMS;
