// AUTO-GENERATED BY scripts/add-practice.mjs
window.CLASSROOM_PRACTICE_ITEMS = [
  {
    "id": "courseware-2026-07-17-articles",
    "title": "26.07.17｜冠词闯关",
    "description": "冠词课堂即时练习，共 24 题，覆盖 a/an、the、零冠词与易混辨析",
    "icon": "screen",
    "tone": "purple",
    "path": "courseware/26.07.17｜冠词闯关.html"
  },
  {
    "id": "courseware-2026-07-17",
    "title": "26.07.17｜名词变身工厂",
    "description": "名词单复数课堂即时练习，共 14 题",
    "icon": "screen",
    "tone": "purple",
    "path": "courseware/26.07.17｜名词变身工厂.html"
  },
  {
    "id": "courseware-2026-07-16",
    "title": "26.07.16",
    "description": "代词与 be 动词课堂即时练习",
    "icon": "screen",
    "tone": "purple",
    "path": "courseware/26.07.16.html"
  },
  {
    "id": "sentence-structure-2026-07-15",
    "title": "26.07.15",
    "description": "句子骨架、句型判断、句型转换与扩句练习",
    "icon": "screen",
    "tone": "purple",
    "path": "courseware/26.07.15.html"
  }
];
// Legacy alias: keep existing integrations and historical pages working.
window.COURSEWARE_ITEMS = window.CLASSROOM_PRACTICE_ITEMS;
