(function(root,factory){const api=factory(root&&root.VocabularyAdventureCore,root&&root.VocabularyAdventureReview);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.VocabularyConsolidationCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(defaultCore,defaultReview){
'use strict';
const MAX_ITEMS=6,RESULTS=new Set(['D','H','F']),STATUSES=new Set(['pending','active','completed']);
const BASIC_FALLBACK=['wordToMeaning','meaningToWord','audioToMeaning','audioToWord'];
const plain=v=>!!v&&typeof v==='object'&&!Array.isArray(v);
const clone=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
const text=v=>String(v==null?'':v).trim().replace(/\s+/g,' ');
const key=v=>text(v).toLocaleLowerCase();
function stateKeyForUser(user){user=text(user);return user==='sister'||user==='brother'?`vocab_adventure_v1_${user}`:'';}
async function persistPrepared(current,prepared,save){if(typeof save!=='function')throw new TypeError('saveState is required');return await save(prepared)?{ok:true,state:prepared}:{ok:false,state:current};}
function normalizeItem(v){if(!plain(v))return null;const wordKey=key(v.wordKey||v.word);if(!wordKey)return null;return{wordKey,word:text(v.word||wordKey),sourceResult:RESULTS.has(v.sourceResult)?v.sourceResult:'',previousTaskType:text(v.previousTaskType),taskType:text(v.taskType),status:v.status==='completed'?'completed':'pending',correct:v.correct===true?true:v.correct===false?false:null,attempts:Math.max(0,Math.floor(Number(v.attempts)||0))};}
function normalize(value,session){const source=plain(value)?value:{},items=Array.isArray(source.items)?source.items.map(normalizeItem).filter(Boolean):[];let cursor=Math.min(items.length,Math.max(0,Math.floor(Number(source.cursor)||0)));let status=STATUSES.has(source.status)?source.status:'pending';if(!items.length||(cursor>=items.length&&items.every(x=>x.status==='completed')))status='completed';if(status==='completed')cursor=items.length;else if(cursor>0)status='active';return{status,items,cursor,generatedFromPlanLength:Math.max(0,Math.floor(Number(source.generatedFromPlanLength)||(session&&session.plan&&session.plan.length)||0))};}
function selectItems(session,maxItems=MAX_ITEMS){const limit=Math.max(0,Math.floor(Number(maxItems)||MAX_ITEMS));if(!limit)return[];const done=Array.isArray(session&&session.plan)?session.plan.filter(x=>x&&x.status==='completed'):[],seen=new Set();const collect=result=>done.reduce((out,item)=>{if(out.length>=limit||item.result!==result)return out;const wordKey=key(item.wordKey||item.word);if(!wordKey||seen.has(wordKey))return out;seen.add(wordKey);out.push({wordKey,word:text(item.word||wordKey),sourceResult:result,previousTaskType:text(item.confirmationTaskType||item.taskType),taskType:'',status:'pending',correct:null,attempts:0});return out;},[]);const failed=collect('F');return failed.length>=limit?failed.slice(0,limit):[...failed,...collect('H')].slice(0,limit);}
function ensure(stateValue,core=defaultCore){const raw=plain(stateValue)?stateValue:{},state=core&&typeof core.normalizeVocabularyAdventureState==='function'?core.normalizeVocabularyAdventureState(raw):clone(raw);if(!state||!state.session)return state;const rawSession=plain(raw.session)?raw.session:{};let consolidation=rawSession.consolidation?normalize(rawSession.consolidation,state.session):null;if(!consolidation&&state.session.completed){const items=selectItems(state.session);consolidation=normalize({status:items.length?'pending':'completed',items,cursor:0,generatedFromPlanLength:state.session.plan.length},state.session);}if(consolidation)state.session={...state.session,consolidation};return state;}
function currentItem(stateValue,core=defaultCore){const state=ensure(stateValue,core),c=state&&state.session&&state.session.consolidation;return !c||c.status==='completed'?null:c.items[c.cursor]||null;}
function prepareResult(stateValue,input,core=defaultCore){const state=ensure(stateValue,core),session=state&&state.session,c=session&&session.consolidation,s=plain(input)?input:{};if(!session||!session.completed||!c||c.status==='completed')throw Object.assign(new Error('Consolidation unavailable'),{code:'CONSOLIDATION_UNAVAILABLE'});if(!Number.isInteger(Number(s.expectedCursor))||Number(s.expectedCursor)!==c.cursor)throw Object.assign(new Error('Consolidation cursor changed'),{code:'CURSOR_MISMATCH'});const item=c.items[c.cursor];if(!item||item.wordKey!==key(s.wordKey))throw Object.assign(new Error('Consolidation word mismatch'),{code:'WORD_MISMATCH'});const taskType=text(s.taskType);if(!taskType||taskType===item.previousTaskType)throw Object.assign(new Error('Consolidation task type must differ'),{code:'INVALID_TASK_TYPE'});const items=c.items.map((x,i)=>i===c.cursor?{...x,taskType,status:'completed',correct:s.correct===true,attempts:Math.max(1,Math.floor(Number(s.attempts)||1))}:{...x}),cursor=c.cursor+1,done=cursor>=items.length,next=clone(state);next.session.consolidation={...c,status:done?'completed':'active',items,cursor:done?items.length:cursor};return ensure(next,core);}
function direction(type){type=text(type);if(/audio/i.test(type))return'audio';if(/missing|letter|spelling|phonetic/i.test(type))return'form';if(/collocation|example|sentence/i.test(type))return'usage';if(/meaningToWord/i.test(type))return'meaning-to-word';if(/wordToMeaning|visualMatch/i.test(type))return'word-to-meaning';return'other';}
function taskCandidates(previous,registry){const available=new Set(Object.keys(registry||{})),d=direction(previous);const preferred=d==='word-to-meaning'?['audioToMeaning','missingLetters','meaningToWord','audioSpelling','letterOrder','audioToWord']:d==='audio'?['missingLetters','letterOrder','wordToMeaning','meaningToWord','audioSpelling']:d==='form'?['wordToMeaning','audioToMeaning','meaningToWord','visualMatch','audioToWord']:d==='usage'?['wordToMeaning','meaningToWord','audioToMeaning','audioToWord','visualMatch']:['audioToMeaning','missingLetters','meaningToWord','wordToMeaning','letterOrder','audioToWord'];const fallback=['wordToMeaning','meaningToWord','audioToMeaning','audioToWord','missingLetters','letterOrder','audioSpelling','visualMatch','phoneticToMeaning','phoneticToWord'];return[...new Set([...preferred,...fallback])].filter(t=>t!==previous&&available.has(t));}
function mapChoice(q){return q&&q.ok?{...q,interaction:'choice',questionType:q.questionType||q.taskType,category:'basic',requiresUsageConfirmation:false}:q;}
function buildQuestion(options){const o=plain(options)?options:{},core=o.core||defaultCore,review=o.review||defaultReview,state=ensure(o.state,core),item=currentItem(state,core);if(!item)return{ok:false,reason:'CONSOLIDATION_COMPLETE'};const candidates=Array.isArray(o.candidates)?o.candidates:[],candidate=candidates.find(x=>key(x&&(x.key||x.word))===item.wordKey);if(!candidate)return{ok:false,reason:'WORD_NOT_VISIBLE',wordKey:item.wordKey};const registry=review&&review.VocabularyAdventureReviewTypes||{},context={session:state.session,planItem:{wordKey:item.wordKey,word:item.word,taskType:'',reviewReason:item.sourceResult==='F'?'failed':'hinted'},planIndex:state.session.plan.length+state.session.consolidation.cursor,wordState:state.words&&state.words[item.wordKey]||{},card:candidate.card,allCards:candidates,userKey:o.userKey||'',reason:item.sourceResult==='F'?'failed':'hinted'},attemptedTypes=[];for(const taskType of taskCandidates(item.previousTaskType,registry)){attemptedTypes.push(taskType);const d=registry[taskType],q=d&&typeof d.build==='function'?d.build({...context,taskType}):null;if(q&&q.ok&&text(q.questionType||q.taskType)!==item.previousTaskType)return{...q,questionType:text(q.questionType||q.taskType||taskType),taskType:text(q.taskType||q.questionType||taskType),consolidation:true,attemptedTypes};}for(const taskType of BASIC_FALLBACK){if(taskType===item.previousTaskType||attemptedTypes.includes(taskType))continue;attemptedTypes.push(taskType);const q=core&&typeof core.buildVocabularyAdventureQuestion==='function'?mapChoice(core.buildVocabularyAdventureQuestion({candidates,sessionDate:state.session.date,wordKey:item.wordKey,planIndex:state.session.plan.length+state.session.consolidation.cursor,taskType,lastTaskType:item.previousTaskType,seed:`${o.userKey||''}|consolidation`})):null;if(q&&q.ok&&text(q.questionType||q.taskType)!==item.previousTaskType)return{...q,questionType:text(q.questionType||q.taskType||taskType),taskType:text(q.taskType||q.questionType||taskType),consolidation:true,attemptedTypes,fallback:true};}return{ok:false,reason:'NO_SAFE_QUESTION',wordKey:item.wordKey,attemptedTypes};}
function attemptTracker(){let count=0,locked=false;return{answer(correct){if(locked)return{kind:'locked',attemptCount:count};count++;if(correct){locked=true;return{kind:'result',result:count===1?'D':'H',attemptCount:count};}if(count===1)return{kind:'hint',attemptCount:count};locked=true;return{kind:'result',result:'F',attemptCount:count};},snapshot:()=>({attemptCount:count,locked})};}
return Object.freeze({MAX_ITEMS,MAX_CONSOLIDATION_ITEMS:MAX_ITEMS,stateKeyForUser,vocabularyAdventureStateKeyForUser:stateKeyForUser,persistPrepared,persistPreparedVocabularyState:persistPrepared,normalizeItem,normalizeConsolidationItem:normalizeItem,normalize,normalizeConsolidation:normalize,selectItems,selectVocabularyConsolidationItems:selectItems,ensure,ensureVocabularyConsolidation:ensure,currentItem,currentConsolidationItem:currentItem,prepareResult,prepareVocabularyConsolidationResult:prepareResult,direction,taskDirection:direction,taskCandidates,consolidationTaskCandidates:taskCandidates,buildQuestion,buildVocabularyConsolidationQuestion:buildQuestion,attemptTracker,createAttemptTracker:attemptTracker});
});
