(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.VocabularyConsolidationView=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const LABELS={visualMatch:'找出对应的英文和提示',wordToMeaning:'看单词，选择正确意思',meaningToWord:'看意思，选择正确单词',audioToMeaning:'听一听，选择正确意思',audioToWord:'听一听，选择正确单词',phoneticToMeaning:'看音标，选择正确意思',phoneticToWord:'看音标，选择正确单词',missingLetters:'补全缺少的字母',letterOrder:'按顺序拼出单词',audioSpelling:'听发音，拼写单词',collocationCloze:'完成固定搭配',exampleCloze:'完成例句',sentenceOrder:'排列完整句子'};
const text=v=>String(v==null?'':v).trim();
const escape=v=>String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
function cardLine(item){if(typeof item==='string')return item;if(!item||typeof item!=='object')return'';return[item.label||item.type||'',item.form||item.word||item.phrase||'',item.meaning||'',item.example||''].filter(Boolean).join(' · ');}
function fullCard(card){card=card&&typeof card==='object'?card:{};const meta=[card.pos,card.phonetic].filter(Boolean).map(escape).join(' · '),sections=[['固定搭配',card.collocations],['词形变化',card.irregularForms],['近义词',card.synonyms],['词族',card.wordFamily]].map(([title,values])=>{const entries=(Array.isArray(values)?values:[]).map(cardLine).filter(Boolean);return entries.length?`<section><h4>${title}</h4>${entries.map(v=>`<p>${escape(v)}</p>`).join('')}</section>`:'';}).join('');return`<div class="vocabulary-adventure-full-card"><div class="vocabulary-adventure-card-heading"><span class="vocabulary-adventure-card-emoji">${escape(card.emoji||'📝')}</span><div><h2>${escape(card.word||'')}</h2><p>${escape(card.meaning||'')}</p>${meta?`<small>${meta}</small>`:''}</div><button type="button" class="vocabulary-adventure-speak" onclick="speakVocabularyAdventureCurrent()" aria-label="播放单词发音">🔊</button></div>${sections}${card.tip?`<section class="vocabulary-adventure-tip"><h4>提示</h4><p>${escape(card.tip)}</p></section>`:''}</div>`;}
function prompt(question){const type=text(question&& (question.questionType||question.taskType));return /^audio/i.test(type)?'<button type="button" class="vocabulary-adventure-audio-prompt" onclick="speakVocabularyAdventureCurrent()"><span>🔊</span> 再听一次</button>':`<div class="vocabulary-adventure-prompt-text">${escape(question&&question.prompt||'')}</div>`;}
function choice(question,handler){return`${prompt(question)}<div class="vocabulary-adventure-hint" id="vocabularyAdventureReviewHint" hidden></div><div class="vocabulary-adventure-options" id="vocabularyAdventureReviewOptions">${(question.options||[]).map((o,i)=>`<button type="button" data-option-index="${i}" onclick="${handler}(${i})">${escape(o.label)}</button>`).join('')}</div>`;}
function input(question){return`${prompt(question)}<div class="vocabulary-adventure-hint" id="vocabularyAdventureReviewHint" hidden></div><div class="vocabulary-adventure-input-row"><input id="vocabularyAdventureReviewInput" autocomplete="off" autocapitalize="none" spellcheck="false" aria-label="输入答案"><button type="button" onclick="submitVocabularyAdventureReviewInput()">确认</button></div>`;}
function order(question,selectedIds){const chosen=new Set(selectedIds),selected=selectedIds.map(id=>question.tokens.find(t=>t.id===id)).filter(Boolean);return`<div class="vocabulary-adventure-order-prompt">${escape(question.prompt||'')}</div><div class="vocabulary-adventure-order-answer" aria-label="当前排列">${selected.length?selected.map(t=>`<span>${escape(t.label)}</span>`).join(''):'<small>依次点击下面的内容</small>'}</div><div class="vocabulary-adventure-order-pool">${(question.tokens||[]).map(t=>`<button type="button" ${chosen.has(t.id)?'disabled':''} onclick="selectVocabularyAdventureReviewToken('${escape(t.id)}')">${escape(t.label)}</button>`).join('')}</div><div class="vocabulary-adventure-order-actions"><button type="button" onclick="clearVocabularyAdventureReviewOrder()">重排</button><button type="button" class="primary" onclick="submitVocabularyAdventureReviewOrder()">确认</button></div><div class="vocabulary-adventure-hint" id="vocabularyAdventureReviewHint" hidden></div>`;}
function match(question,state){return`<div class="vocabulary-adventure-match-status">已配对 ${state.matchedPairs.size} / ${question.pairs.length}</div><div class="vocabulary-adventure-match-board">${(question.cards||[]).map(card=>{const matched=state.matchedCards.has(card.id),selected=state.selectedId===card.id;return`<button type="button" class="${matched?'is-matched':''} ${selected?'is-selected':''}" ${matched?'disabled':''} aria-pressed="${selected}" onclick="selectVocabularyAdventureMatchCard('${escape(card.id)}')"><small>${card.side==='word'?'英文':'提示'}</small><span>${escape(card.label)}</span></button>`;}).join('')}</div>`;}
function question(question,mode,stage,selectedIds,matchState){let body='';const handler=mode==='screening'?'answerVocabularyAdventure':'answerVocabularyAdventureReviewChoice';if(question.interaction==='choice')body=choice(question,handler);if(question.interaction==='input')body=input(question);if(question.interaction==='order')body=order(question,selectedIds||[]);if(question.interaction==='match')body=match(question,matchState);const consolidation=mode==='consolidation',confirmation=stage==='confirmation';return`<div class="vocabulary-adventure-question ${mode!=='screening'?'is-review':''} ${confirmation?'is-confirmation':''}"><div class="vocabulary-adventure-question-label">${consolidation?'再练一次 · ':''}${confirmation?'再确认一次 · ':''}${escape(LABELS[question.questionType||question.taskType]||'选择正确答案')}</div>${confirmation?'<p class="vocabulary-adventure-confirmation-note">意思记住了，我们再多练一次。</p>':''}${body}</div>`;}
function screening(question){return`<div class="vocabulary-adventure-question"><div class="vocabulary-adventure-question-label">${escape(LABELS[question.taskType]||'选择正确答案')}</div>${prompt(question)}<div class="vocabulary-adventure-hint" id="vocabularyAdventureHint" hidden></div><div class="vocabulary-adventure-options" id="vocabularyAdventureOptions">${(question.options||[]).map((o,i)=>`<button type="button" data-option-index="${i}" onclick="answerVocabularyAdventure(${i})">${escape(o.label)}</button>`).join('')}</div></div>`;}
function saved(feedback){const failed=feedback.result==='F',usage=feedback.outcomeDetail==='usageWeak';if(failed)return`<div class="vocabulary-adventure-result is-failed"><div class="vocabulary-adventure-result-title">我们再认识一次这个词。</div>${fullCard(feedback.card)}</div>`;const title=usage?'意思记住了，我们再多练一次。':feedback.result==='H'?'提示帮你想起来了。':'找到了！';return`<div class="vocabulary-adventure-result ${feedback.result==='H'?'is-hinted':'is-direct'}"><div class="vocabulary-adventure-result-icon">${feedback.result==='H'?'💡':'✨'}</div><h2>${title}</h2><p>${escape(feedback.card.word)} · ${escape(feedback.card.meaning)}</p></div>`;}
function summary(hasItems){return`<div class="vocabulary-adventure-summary"><div class="vocabulary-adventure-terminal-icon">✅</div><h2>今天的词汇探险完成了</h2>${hasItems?'<p class="vocabulary-adventure-summary-note">刚才容易忘的词已经再练过了。</p>':''}<p>今天的进度已经保存。</p></div>`;}
function terminal(title,message,mode){return`<div class="vocabulary-adventure-terminal"><div class="vocabulary-adventure-terminal-icon">${mode==='completed'?'✅':'⚠️'}</div><h2>${escape(title)}</h2><p>${escape(message)}</p></div>`;}
return Object.freeze({LABELS,escape,fullCard,question,screening,saved,summary,terminal});
});
