// Source: Supabase latest vocabulary batch "07.18｜暑假生词1" (2026-07-18)
const reviewWords = Object.freeze([
  { word: 'tidy', phonetic: '/ˈtaɪdi/', meaning: '整洁的', image: 'assets/vocabulary-review/tidy.webp', placeholder: '🧹' },
  { word: 'mess', phonetic: '/mes/', meaning: '杂乱；一团糟', image: 'assets/vocabulary-review/mess.webp', placeholder: '🌀' },
  { word: 'weak', phonetic: '/wiːk/', meaning: '虚弱的', image: 'assets/vocabulary-review/weak.webp', placeholder: '🪫' },
  { word: 'culture', phonetic: '/ˈkʌltʃə/', meaning: '文化', image: 'assets/vocabulary-review/culture.webp', placeholder: '🌏' },
  { word: 'divide', phonetic: '/dɪˈvaɪd/', meaning: '分；划分', image: 'assets/vocabulary-review/divide.webp', placeholder: '✂️' },
  { word: 'foreign', phonetic: '/ˈfɒrən/', meaning: '外国的', image: 'assets/vocabulary-review/foreign.webp', placeholder: '🌍' },
  { word: 'collect', phonetic: '/kəˈlekt/', meaning: '收集', image: 'assets/vocabulary-review/collect.webp', placeholder: '🗂️' },
  { word: 'information', phonetic: '/ˌɪnfəˈmeɪʃən/', meaning: '信息', image: 'assets/vocabulary-review/information.webp', placeholder: 'ℹ️' },
  { word: 'tradition', phonetic: '/trəˈdɪʃən/', meaning: '传统', image: 'assets/vocabulary-review/tradition.webp', placeholder: '🎎' },
  { word: 'festival', phonetic: '/ˈfestɪvəl/', meaning: '节日', image: 'assets/vocabulary-review/festival.webp', placeholder: '🎉' },
  { word: 'celebration', phonetic: '/ˌselɪˈbreɪʃən/', meaning: '庆祝活动', image: 'assets/vocabulary-review/celebration.webp', placeholder: '🎊' },
  { word: 'origami', phonetic: '/ˌɒrɪˈɡɑːmi/', meaning: '折纸', image: 'assets/vocabulary-review/origami.webp', placeholder: '🦢' },
  { word: 'challenging', phonetic: '/ˈtʃælɪndʒɪŋ/', meaning: '有挑战性的', image: 'assets/vocabulary-review/challenging.webp', placeholder: '🧩' },
  { word: 'practice', phonetic: '/ˈpræktɪs/', meaning: '练习', image: 'assets/vocabulary-review/practice.webp', placeholder: '🏋️' },
  { word: 'nervous', phonetic: '/ˈnɜːvəs/', meaning: '紧张的', image: 'assets/vocabulary-review/nervous.webp', placeholder: '😰' },
  { word: 'power', phonetic: '/ˈpaʊə/', meaning: '电力；力量', image: 'assets/vocabulary-review/power.webp', placeholder: '⚡' },
  { word: 'go', phonetic: '/ɡəʊ/', meaning: '去；走', image: 'assets/vocabulary-review/go.webp', placeholder: '➡️' },
  { word: 'despite', phonetic: '/dɪˈspaɪt/', meaning: '尽管', image: 'assets/vocabulary-review/despite.webp', placeholder: '🌧️' },
  { word: 'difficulty', phonetic: '/ˈdɪfɪkəlti/', meaning: '困难', image: 'assets/vocabulary-review/difficulty.webp', placeholder: '🧗' },
  { word: 'insist', phonetic: '/ɪnˈsɪst/', meaning: '坚持；坚决要求', image: 'assets/vocabulary-review/insist.webp', placeholder: '📌' },
  { word: 'task', phonetic: '/tɑːsk/', meaning: '任务', image: 'assets/vocabulary-review/task.webp', placeholder: '✅' },
  { word: 'hold', phonetic: '/həʊld/', meaning: '举办；握住', image: 'assets/vocabulary-review/hold.webp', placeholder: '🤲' },
  { word: 'speech', phonetic: '/spiːtʃ/', meaning: '演讲', image: 'assets/vocabulary-review/speech.webp', placeholder: '🎤' },
  { word: 'contest', phonetic: '/ˈkɒntest/', meaning: '比赛；竞赛', image: 'assets/vocabulary-review/contest.webp', placeholder: '🏆' },
  { word: 'exhibit', phonetic: '/ɪɡˈzɪbɪt/', meaning: '展品', image: 'assets/vocabulary-review/exhibit.webp', placeholder: '🏺' },
  { word: 'numerous', phonetic: '/ˈnjuːmərəs/', meaning: '数量众多的', image: 'assets/vocabulary-review/numerous.webp', placeholder: '🔢' },
  { word: 'valuable', phonetic: '/ˈvæljuəbəl/', meaning: '有价值的', image: 'assets/vocabulary-review/valuable.webp', placeholder: '💎' }
]);
