(function(root,factory){const api=factory(root,root&&root.VocabularyConsolidationCore,root&&root.VocabularyConsolidationView,root&&root.VocabularyAdventureCore,root&&root.VocabularyAdventureReview);if(typeof module==='object'&&module.exports)module.exports=api;if(root&&typeof module!=='object')Object.assign(root,api);})(typeof globalThis!=='undefined'?globalThis:this,function(root,consolidation,view,core,review){
'use strict';
const text=v=>String(v==null?'':v).trim().replace(/\s+/g,' '),key=v=>text(v).toLocaleLowerCase(),clone=v=>JSON.parse(JSON.stringify(v));
const runtime={user:'',state:null,candidates:[],card:null,question:null,original:null,stage:'',tracker:null,order:[],match:null,disabled:new Set(),prepared:null,saved:null,saving:false,initialPending:false,error:''};
const el=id=>root.document&&root.document.getElementById(id);
function reset(){Object.assign(runtime,{user:'',state:null,candidates:[],card:null,question:null,original:null,stage:'',tracker:null,order:[],match:null,disabled:new Set(),prepared:null,saved:null,saving:false,initialPending:false,error:''});}
function user(){const value=text(root.currentUser||(typeof currentUser!=='undefined'?currentUser:''));return value==='sister'||value==='brother'?value:'';}
function body(html,mode){const node=el('vocabularyAdventureBody');if(node){node.dataset.mode=mode||'';node.innerHTML=html;}}
function feedback(message,tone,label,action){const copy=el('vocabularyAdventureFeedbackText'),button=el('vocabularyAdventureAction');if(copy){copy.textContent=message||'';copy.dataset.tone=tone||'';}if(button){button.hidden=!label;button.textContent=label||'';button.onclick=action&&typeof root[action]==='function'?root[action]:null;}}
function terminal(title,message,mode='error'){body(view.terminal(title,message,mode),mode);feedback('','','返回首页','closeVocabularyAdventure');}
function candidates(){return typeof root.collectVisibleVocabularyAdventureCandidates==='function'?root.collectVisibleVocabularyAdventureCandidates():[];}
function cardFor(wordKey){const item=runtime.candidates.find(x=>key(x&&(x.key||x.word))===key(wordKey));return item&&item.card||null;}
async function readState(){const storageKey=consolidation.stateKeyForUser(runtime.user),raw=storageKey&&typeof root.sbGet==='function'?await root.sbGet(storageKey):null;return consolidation.ensure(raw,core);}
async function writeState(state){const storageKey=consolidation.stateKeyForUser(runtime.user);if(!storageKey||typeof root.sbSet!=='function')return false;try{return await root.sbSet(storageKey,consolidation.ensure(state,core))!==false;}catch(error){console.warn('Vocabulary adventure state save failed',error);root.showStorageError?.(error);return false;}}
function planItem(){const s=runtime.state&&runtime.state.session;return s&&!s.completed?s.plan[s.cursor]:null;}
function consolidationItem(){return consolidation.currentItem(runtime.state,core);}
function progress(){const s=runtime.state&&runtime.state.session;if(!s)return;const c=s.consolidation,mainDone=s.plan.filter(x=>x.status==='completed').length,inConsolidation=s.completed&&c&&c.status!=='completed',current=planItem(),stage=el('vocabularyAdventureStageTitle'),phase=el('vocabularyAdventureScreeningProgress'),total=el('vocabularyAdventureTotalProgress'),fill=el('vocabularyAdventureProgressFill'),date=el('vocabularyAdventureSessionDate');if(stage)stage.textContent=inConsolidation?'再练几个刚才遇到的词':current&&current.phase==='review'?'第二站 · 抗遗忘':s.completed?'今日完成':'第一站 · 摸底';if(phase){if(inConsolidation)phase.textContent=`再练 ${c.cursor} / ${c.items.length}`;else if(current&&current.phase==='review'){const list=s.plan.filter(x=>x.phase==='review');phase.textContent=`抗遗忘 ${list.filter(x=>x.status==='completed').length} / ${list.length}`;}else{const list=s.plan.filter(x=>x.phase==='screening');phase.textContent=`摸底 ${list.filter(x=>x.status==='completed').length} / ${list.length}`;}}const all=s.plan.length+(c?c.items.length:0),done=mainDone+(c?c.cursor:0);if(total)total.textContent=`今日计划 ${done} / ${all}`;if(fill)fill.style.width=`${all?done/all*100:100}%`;if(date){const today=core.localDateKey(new Date());date.textContent=s.date===today?'':`继续 ${s.date} 未完成计划`;date.hidden=s.date===today;}}
function context(item){return{session:runtime.state.session,planItem:item,planIndex:runtime.state.session.cursor,wordState:runtime.state.words[item.wordKey],card:runtime.card,allCards:runtime.candidates,userKey:runtime.user};}
function initQuestion(question,stage){runtime.question=question;runtime.original=question;runtime.stage=stage;runtime.tracker=consolidation.attemptTracker();runtime.order=[];runtime.match=question.interaction==='match'?{selectedId:'',matchedCards:new Set(),matchedPairs:new Set(),errors:0}:null;renderQuestion();}
function renderQuestion(){const mode=runtime.stage==='consolidation'?'consolidation':runtime.stage==='screening'?'screening':'review';body(mode==='screening'?view.screening(runtime.question):view.question(runtime.question,mode,runtime.stage,runtime.order,runtime.match),runtime.question.interaction==='match'?'match':mode);feedback(mode==='consolidation'?'想一想刚才遇到的词':'请选择答案','','','');if(/^audio/i.test(text(runtime.question.questionType||runtime.question.taskType)))root.setTimeout(()=>speakVocabularyAdventureCurrent(),120);el('vocabularyAdventureReviewInput')?.focus();}
function prepareReview(item){runtime.card=cardFor(item.wordKey);const q=runtime.card&&review.buildVocabularyAdventureReviewQuestion(context(item));if(!q||!q.ok)return false;initQuestion(q,'review');return true;}
function prepareConsolidation(){const item=consolidationItem();runtime.card=item&&cardFor(item.wordKey);const q=runtime.card&&consolidation.buildQuestion({state:runtime.state,candidates:runtime.candidates,userKey:runtime.user,core,review});if(!q||!q.ok)return false;initQuestion(q,'consolidation');return true;}
function showSaved(){if(!runtime.saved)return false;body(view.saved(runtime.saved),'result');const failed=runtime.saved.result==='F',isConsolidation=runtime.saved.phase==='consolidation';feedback(isConsolidation&&failed?'这个词已经看过完整单词卡，可以继续。':failed?'我们再认识一次这个词。':'进度已保存。',failed?'failed':runtime.saved.result==='H'?'hinted':'direct','继续','nextVocabularyAdventure');return true;}
function renderCurrent(){progress();const s=runtime.state&&runtime.state.session;if(!s)return terminal('暂时无法开始','没有可用的探险计划。');if(showSaved())return;if(s.completed){const c=s.consolidation;if(c&&c.status!=='completed'){if(!runtime.question&&!prepareConsolidation())return terminal('暂时不能继续','当前单词暂时不能安全出题，请返回首页后重试。');return;}body(view.summary(!!(c&&c.items.length)),'summary');feedback('今天的词汇探险完成了','direct','返回首页','closeVocabularyAdventure');return;}const item=planItem();if(!item||item.status!=='pending')return terminal('计划状态异常','请返回首页后重试。');runtime.card=cardFor(item.wordKey);if(!runtime.card)return terminal('无法读取当前单词','这张单词卡当前不可用。');if(item.phase==='review'){if(!runtime.question&&!prepareReview(item))terminal('暂时不能继续','当前单词暂时不能安全出题，请返回首页后重试。');return;}const previous=runtime.state.words[item.wordKey];const q=core.buildVocabularyAdventureQuestion({candidates:runtime.candidates,sessionDate:s.date,wordKey:item.wordKey,planIndex:s.cursor,lastTaskType:previous&&previous.lastTaskType});if(!q||!q.ok)return terminal('无法生成题目','当前单词暂时不能安全出题。');runtime.question=q;runtime.original=q;runtime.stage='screening';runtime.tracker=consolidation.attemptTracker();runtime.disabled=new Set();renderQuestion();}
function hint(){const node=el(runtime.stage==='screening'?'vocabularyAdventureHint':'vocabularyAdventureReviewHint');if(node){const first=text(runtime.card&&runtime.card.word).charAt(0).toUpperCase();node.innerHTML=`<strong>${first?`首字母：${view.escape(first)}…`:'再听一次'}</strong><button type="button" onclick="speakVocabularyAdventureCurrent()">🔊 再听一次</button>`;node.hidden=false;}feedback('再试一次，看看提示。','hinted','','');}
async function savePrepared(){if(!runtime.prepared||runtime.saving)return;runtime.saving=true;feedback('正在保存…','','','');const prepared=runtime.prepared,saved=await writeState(prepared.state);runtime.saving=false;if(!saved)return feedback('保存失败，进度还没有前进。','failed','重新保存','retryVocabularyAdventureResultSave');runtime.state=prepared.state;runtime.saved={...prepared.meta,card:runtime.card};runtime.prepared=null;renderCurrent();}
async function prepareMain(result,outcomeDetail='',confirmationTaskType=''){const s=runtime.state.session,item=s.plan[s.cursor],original=runtime.original||runtime.question;let next;if(item.phase==='review')next=core.prepareVocabularyAdventureReviewResult(runtime.state,{expectedCursor:s.cursor,wordKey:item.wordKey,taskType:original.questionType||original.taskType,confirmationTaskType,outcomeDetail,result,reviewedAt:new Date()});else next=core.prepareVocabularyAdventureResult(runtime.state,{expectedCursor:s.cursor,wordKey:item.wordKey,taskType:runtime.question.taskType,result,reviewedAt:new Date()});next=consolidation.ensure(next,core);runtime.prepared={state:next,meta:{phase:item.phase,result,taskType:original.questionType||original.taskType,outcomeDetail}};await savePrepared();}
async function prepareConsolidation(correct,attempts){const c=runtime.state.session.consolidation,item=c.items[c.cursor],taskType=text(runtime.question.questionType||runtime.question.taskType),next=consolidation.prepareResult(runtime.state,{expectedCursor:c.cursor,wordKey:item.wordKey,taskType,correct,attempts},core);runtime.prepared={state:next,meta:{phase:'consolidation',result:correct?(attempts===1?'D':'H'):'F',taskType,outcomeDetail:''}};await savePrepared();}
function meaningConfirmation(){const item=planItem();runtime.original=runtime.original||runtime.question;const q=review.buildVocabularyAdventureMeaningConfirmation(context(item));if(!q||!q.ok){terminal('暂时不能继续','当前单词暂时不能安全出题。');return false;}runtime.question=q;runtime.stage='confirmation';runtime.tracker=null;runtime.order=[];runtime.match=null;renderQuestion();return true;}
async function finish(correct){if(!runtime.question||runtime.prepared||runtime.saving)return;if(runtime.stage==='confirmation'){const usage=!!(runtime.original&&runtime.original.requiresUsageConfirmation&&correct);await prepareMain(correct?'H':'F',usage?'usageWeak':'',runtime.question.questionType);return;}if(runtime.stage==='review'&&runtime.question.requiresUsageConfirmation){if(correct)await prepareMain('D');else meaningConfirmation();return;}const result=runtime.tracker.answer(correct);if(result.kind==='hint')return hint();if(result.kind!=='result')return;if(runtime.stage==='consolidation')await prepareConsolidation(correct,result.attemptCount);else await prepareMain(result.result);}
async function answerVocabularyAdventure(index){if(runtime.stage!=='screening'||!runtime.question)return;index=Number(index);if(!runtime.question.options[index]||runtime.disabled.has(index))return;const correct=index===runtime.question.correctIndex;if(!correct&&runtime.tracker.snapshot().attemptCount===0){runtime.disabled.add(index);const button=el('vocabularyAdventureOptions')?.querySelectorAll('button')[index];if(button){button.disabled=true;button.classList.add('is-wrong');}}await finish(correct);}
async function answerVocabularyAdventureReviewChoice(index){if(!runtime.question||runtime.question.interaction!=='choice')return;index=Number(index);const correct=review.gradeVocabularyAdventureReviewQuestion(runtime.question,index);if(!correct&&runtime.stage!=='confirmation'&&runtime.tracker&&runtime.tracker.snapshot().attemptCount===0){const button=el('vocabularyAdventureReviewOptions')?.querySelectorAll('button')[index];if(button){button.disabled=true;button.classList.add('is-wrong');}}await finish(correct);}
async function submitVocabularyAdventureReviewInput(){const input=el('vocabularyAdventureReviewInput');if(input&&runtime.question&&runtime.question.interaction==='input')await finish(review.gradeVocabularyAdventureReviewQuestion(runtime.question,input.value));}
function selectVocabularyAdventureReviewToken(id){if(runtime.question&&runtime.question.interaction==='order'&&runtime.question.tokens.some(t=>t.id===id)&&!runtime.order.includes(id)){runtime.order.push(id);renderQuestion();}}
function clearVocabularyAdventureReviewOrder(){runtime.order=[];renderQuestion();}
async function submitVocabularyAdventureReviewOrder(){if(runtime.question&&runtime.question.interaction==='order')await finish(review.gradeVocabularyAdventureReviewQuestion(runtime.question,runtime.order));}
async function selectVocabularyAdventureMatchCard(id){const q=runtime.question,m=runtime.match;if(!q||q.interaction!=='match'||!m||m.matchedCards.has(id))return;const card=q.cards.find(x=>x.id===id);if(!card)return;if(!m.selectedId){m.selectedId=id;renderQuestion();return;}if(m.selectedId===id){m.selectedId='';renderQuestion();return;}const first=q.cards.find(x=>x.id===m.selectedId),paired=first&&first.pairKey===card.pairKey&&first.side!==card.side;if(paired){m.matchedCards.add(first.id);m.matchedCards.add(card.id);m.matchedPairs.add(card.pairKey);}else m.errors++;m.selectedId='';renderQuestion();if(m.matchedPairs.size===q.pairs.length){if(runtime.stage==='consolidation')await prepareConsolidation(m.errors===0,m.errors===0?1:2);else{const outcome=review.visualMatchOutcome(m.errors);if(outcome.requiresConfirmation)meaningConfirmation();else await prepareMain(outcome.result);}}else feedback(paired?'配对成功':'再试一次，看看提示。',paired?'direct':'hinted','','');}
async function retryVocabularyAdventureResultSave(){await savePrepared();}
async function retryVocabularyAdventureInitialSave(){if(!runtime.initialPending||!runtime.state||runtime.saving)return;runtime.saving=true;feedback('正在保存…','','','');const saved=await writeState(runtime.state);runtime.saving=false;if(!saved)return feedback('保存失败，进度还没有前进。','failed','重新保存','retryVocabularyAdventureInitialSave');runtime.initialPending=false;renderCurrent();}
function nextVocabularyAdventure(){if(runtime.prepared||runtime.saving)return;runtime.saved=null;runtime.card=null;runtime.question=null;runtime.original=null;runtime.stage='';runtime.tracker=null;runtime.order=[];runtime.match=null;runtime.disabled=new Set();renderCurrent();}
function speakVocabularyAdventureCurrent(){if(runtime.card&&runtime.card.word)root.speakEnglish?.(runtime.card.word);}
async function openVocabularyAdventure(){runtime.user=user();if(!runtime.user)return;reset();runtime.user=user();root.showScreen?.('screenVocabularyAdventure');body('<div class="vocabulary-adventure-loading">正在准备今日探险…</div>','loading');feedback('','','','');try{runtime.candidates=candidates();let state=await readState(),unfinished=!!(state&&state.session&&state.session.completed&&state.session.consolidation&&state.session.consolidation.status!=='completed');const resolved=unfinished?{action:'resumed',state}:core.resolveVocabularyAdventureSession({candidates:runtime.candidates,state,today:core.localDateKey(new Date())});runtime.state=consolidation.ensure(resolved.state,core);if(resolved.action==='created'&&!await writeState(runtime.state)){runtime.initialPending=true;progress();body('<div class="vocabulary-adventure-terminal"><div class="vocabulary-adventure-terminal-icon">☁️</div><h2>今日计划尚未保存</h2><p>保存成功后才能开始答题。</p></div>','error');feedback('保存失败，进度还没有前进。','failed','重新保存','retryVocabularyAdventureInitialSave');return;}renderCurrent();}catch(error){runtime.error=error&&error.message||'读取探险状态失败';terminal('无法开始探险',runtime.error);}}
function closeVocabularyAdventure(){if(runtime.prepared||runtime.initialPending){const discard=root.confirm?root.confirm('还有未保存内容。确定返回首页吗？'):false;if(!discard)return;}try{root.speechSynthesis?.cancel();}catch(_){}reset();root.showScreen?.('screenHome');root.loadHome?.();}
function updateVocabularyAdventurePreviewEntry(){const entry=el('vocabularyAdventurePreviewEntry');if(entry)entry.hidden=!user();}
return{updateVocabularyAdventurePreviewEntry,resetVocabularyAdventurePlayerRuntime:reset,openVocabularyAdventure,closeVocabularyAdventure,answerVocabularyAdventure,answerVocabularyAdventureReviewChoice,submitVocabularyAdventureReviewInput,selectVocabularyAdventureReviewToken,clearVocabularyAdventureReviewOrder,submitVocabularyAdventureReviewOrder,selectVocabularyAdventureMatchCard,retryVocabularyAdventureResultSave,retryVocabularyAdventureInitialSave,nextVocabularyAdventure,speakVocabularyAdventureCurrent,__getVocabularyConsolidationRuntime:()=>runtime};
});
